### ISSUE TITLE
I am getting this error while running the bot

### ISSUE THREAD

**Issue by DevTDubs** [SkylerHere/SofieBot#3]
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    bot = discord.Bot(intents=intents)
AttributeError: module 'discord' has no attribute 'Bot'

**Comment by SkylerHere** [comment]
Where do you host/run the bot? 
And are you using discordpy? Cause pycord uses Bot and other command arguments that can create conflict with discordpy. Plus, discordpy uses Client instead of Bot

**Comment by DevTDubs** [comment]
> 

Replit

**Comment by SkylerHere** [comment]
I'm currently updating my README.md for Replit instructions

**Comment by SkylerHere** [comment]
Ready. Check the [instructions](https://github.com/SkylerHere/SofieBot/blob/master/README.md)

**Comment by SkylerHere** [comment]
Refresh the page there. I added something important last minute

**Comment by SkylerHere** [comment]
Did it work?
